;;; run.scm -- CLI functions for the generic KB.

(define (print-line x)
  (write x)
  (newline))

(define (cli-recall pattern)
  (let* ((facts (run-to-fixpoint *facts* *rules*))
         (hits (filter (lambda (f) (not (eq? 'fail (match pattern f '())))) facts)))
    (if (null? hits)
        (display "NO_MATCH\n")
        (for-each print-line hits))
    (exit 0)))

(define (cli-check)
  (let* ((facts (run-to-fixpoint *facts* *rules*))
         (cs (find-contradictions facts))
         (dg (find-dangling facts))
         (st (find-structure-errors facts))
         (du (find-duplicates *facts*)))
    (define (report label items)
      (display label)
      (display ": ")
      (if (null? items)
          (display "ok\n")
          (begin
            (newline)
            (for-each
              (lambda (x)
                (display "  ")
                (write x)
                (newline))
              items))))
    (report "contradictions" cs)
    (report "dangling" dg)
    (report "structure" st)
    (report "duplicates" du)
    (exit (if (and (null? cs) (null? st)) 0 1))))

(define (cli-test-fact new)
  (let ((base (run-to-fixpoint *facts* *rules*)))
    (cond
      ((member new base)
       (display "REDUNDANT ")
       (write new)
       (newline)
       (exit 2))
      (else
       (let* ((after (run-to-fixpoint (cons new *facts*) *rules*))
              (cs (find-contradictions after)))
         (if (null? cs)
             (begin
               (display "OK ")
               (write new)
               (newline)
               (display "derived-delta: ")
               (write (filter (lambda (f) (not (member f base))) after))
               (newline)
               (exit 0))
             (begin
               (display "REJECT\n")
               (for-each
                 (lambda (c)
                   (display "  ")
                   (write c)
                   (newline))
                 cs)
               (exit 1))))))))

(define (cli-explain pattern)
  (let* ((result (run-to-fixpoint/explain *facts* *rules*))
         (facts (car result))
         (provenance (cdr result))
         (hits (filter (lambda (f) (not (eq? 'fail (match pattern f '())))) facts)))
    (if (null? hits)
        (display "NO_MATCH\n")
        (for-each
          (lambda (hit)
            (explain-fact hit provenance))
          hits))
    (exit 0)))
